### ISSUE TITLE
Couldn't start kali container

### ISSUE THREAD

**Issue by angsuman** [devec0/kali-lxd-image#2]
lxd version: 2.21
lxc version: 2.21
ubuntu version: 16.04

Couldn't start kali container with the following errors:
Log:
lxc 20180524043302.556 ERROR    lxc_start - start.c:start:1443 - No such file or directory - Failed to exec "/sbin/init".
lxc 20180524043302.557 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc 20180524043302.557 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "kali".
lxc 20180524043302.579 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
lxc 20180524043302.579 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "kali".
lxc 20180524043302.579 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
lxc 20180524043302.579 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

**Comment by ldgregory** [comment]
I have the same problem.
Ubuntu 18.04
LXD 3.13
LXC 3.13

Name: lasting-kodiak
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/05/24 22:50 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc lasting-kodiak 20190524225046.457 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lasting-kodiak 20190524225046.457 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc lasting-kodiak 20190524225046.582 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lasting-kodiak 20190524225046.582 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc lasting-kodiak 20190524225046.847 WARN     conf - conf.c:lxc_setup_devpts:1641 - Invalid argument - Failed to unmount old devpts instance
lxc lasting-kodiak 20190524225046.872 ERROR    start - start.c:start:2064 - No such file or directory - Failed to exec "/sbin/init"
lxc lasting-kodiak 20190524225046.872 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 7)
lxc lasting-kodiak 20190524225046.935 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:864 - Received container state "ABORTING" instead of "RUNNING"
lxc lasting-kodiak 20190524225046.935 ERROR    start - start.c:__lxc_start:1975 - Failed to spawn container "lasting-kodiak"
lxc lasting-kodiak 20190524225046.936 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lasting-kodiak 20190524225046.936 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc 20190524225046.940 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

**Comment by digitalrane** [comment]
This turned out being a really simple problem - Kali moved their packages over to GitLab, so the download of the Kali debootstrap template was silently failing, leaving only a 404 page saved to 'kali-debootstrap'. The 'kali-debootstrap' script is what gets called by debootstrap to install the Kali filesystem, so that part wasn't happening at all, explaining why no `/sbin/init` was present in the image.

If you could both test again with latest master, I've done a clean build on Ubuntu Disco and am able to launch the resulting LXD image and run 'apt-get install kali-linux' without any issues.

**Comment by digitalrane** [comment]
I'm closing this as it works for me now. Feel free to advise if it doesn't work for you.
